exports.up = function(knex) {
    return knex.schema
    .createTable("users", user => {
		user.increments()
		user
        .string("username", 128)
        .notNullable()
        .unique()
        user.string("password")
        .notNullable()
		user.string("first_name")
		user.string("last_name")
		user.string("email")
		.unique()
		user.string("token")
	})
    .createTable("friends", friend => {
		friend.increments()
        friend.integer("follower")
        .notNullable()
		friend.integer("following")
		.notNullable()
		.unsigned()
		.references("id")
		.inTable("users")
		.onUpdate("CASCADE")
		.onDelete("CASCADE")
		friend.string("token")
    })
    .createTable("playlists", playlist => {
        playlist.increments()
        playlist.string("title")
        .notNullable()
        playlist.integer("user_id")
		.notNullable()
		.unsigned()
		.references("id")
		.inTable("users")
		.onUpdate("CASCADE")
		.onDelete("CASCADE")
    })
    .createTable("songs", song => {
		song.increments()
        song.string("title")
        .notNullable()
        song.string("album")
        .notNullable()
        song.string("artist")
        .notNullable()
        song.integer("playlist_id")
		.notNullable()
		.unsigned()
		.references("id")
		.inTable("playlists")
		.onUpdate("CASCADE")
		.onDelete("CASCADE")
    })
}

exports.down = async function(knex) {
    await knex.schema.dropTableIfExists("users")
    await knex.schema.dropTableIfExists("friends")
    await knex.schema.dropTableIfExists("playlists")
    await knex.schema.dropTableIfExists("songs")
}